# Copyright (c) 2018-present, Facebook, Inc.
name 'test_services'
maintainer 'Phil Dibowitz'
maintainer_email 'phil@ipom.com'
license 'Apache-2.0'
description 'Includes all cookbooks not in init for testing purposes'
source_url 'https://github.com/jaymzh/chef-fb-api-cookbooks/'
version '0.0.1'
supports 'centos'
supports 'debian'
supports 'redhat'
supports 'ubuntu'
supports 'fedira'
depends 'pd_openport'
depends 'fb_systemd'
