name: Continuous Integration
on:
  push:
    branches: [main]
  pull_request:
jobs:
  ruby:
    strategy:
      fail-fast: false
      matrix:
        ruby: ['3.1', '3.3']
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Install dependencies
      run: bundle install
    # no specs yet
    #- name: Run rspec
    #  run: ./scripts/run_chefspec
    - name: Run cookstyle
      run: ./scripts/run_cookstyle
  kitchen:
    strategy:
      fail-fast: false
      matrix:
        os:
          - centos-stream-9
          - centos-stream-10
          - debian-12
          - fedora-40
          # needs DNF5 support in Chef.
          # - fedora-41
          - ubuntu-2204
          - ubuntu-2404
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        path: 'chef-fb-api-cookbooks'
    - name: Checkout upstream
      uses: actions/checkout@v4
      with:
        repository: 'facebook/chef-cookbooks'
        path: 'chef-cookbooks'
    - name: Copy upstream cookbooks
      run: ./chef-fb-api-cookbooks/scripts/copy_upstream_cookbooks
    - name: Install Chef
      uses: actionshub/chef-install@2.0.4
      with:
        project: chef-workstation
        version: 25.2.1075
    - name: grab kitchen configs
      run: |
        sudo apt install -y wget
        wget -O ./chef-fb-api-cookbooks/.kitchen.yml https://raw.githubusercontent.com/facebook/chef-cookbooks/refs/heads/main/.kitchen.yml
    - name: Run Kitchen
      uses: actionshub/test-kitchen@main
      with:
        suite: default
        os: ${{ matrix.os }}
        working-directory: './chef-fb-api-cookbooks'
      env:
        CHEF_LICENSE: accept-no-persist
        CHEF_VERSION: 18.6.14
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run Shellcheck
        uses: ludeeus/action-shellcheck@2.0.0
